### ISSUE TITLE
git2consul unable to install due to pinkie-promise being unpublished

### ISSUE THREAD

**Issue by solidspark** [breser/git2consul#167]
It appears the package `pinkie-promise` has been unpublished from npm registry.

```
2552 http 304 https://registry.npmjs.org/pinkie-promise
2553 verbose headers { date: 'Sat, 06 Jan 2018 20:23:46 GMT',
2553 verbose headers   via: '1.1 varnish',
2553 verbose headers   'cache-control': 'max-age=300',
2553 verbose headers   etag: '"5a512d53-211"',
2553 verbose headers   age: '690',
2553 verbose headers   connection: 'keep-alive',
2553 verbose headers   'x-served-by': 'cache-sjc3132-SJC',
2553 verbose headers   'x-cache': 'HIT',
2553 verbose headers   'x-cache-hits': '2',
2553 verbose headers   'x-timer': 'S1515270226.279987,VS0,VE0',
2553 verbose headers   vary: 'Accept-Encoding, Accept' }
2554 silly get cb [ 304,
2554 silly get   { date: 'Sat, 06 Jan 2018 20:23:46 GMT',
2554 silly get     via: '1.1 varnish',
2554 silly get     'cache-control': 'max-age=300',
2554 silly get     etag: '"5a512d53-211"',
2554 silly get     age: '690',
2554 silly get     connection: 'keep-alive',
2554 silly get     'x-served-by': 'cache-sjc3132-SJC',
2554 silly get     'x-cache': 'HIT',
2554 silly get     'x-cache-hits': '2',
2554 silly get     'x-timer': 'S1515270226.279987,VS0,VE0',
2554 silly get     vary: 'Accept-Encoding, Accept' } ]
2555 verbose etag https://registry.npmjs.org/pinkie-promise from cache
2556 verbose get saving pinkie-promise to /Users/ryan/.npm/registry.npmjs.org/pinkie-promise/.cache.json
2557 verbose correctMkdir /Users/ryan/.npm correctMkdir not in flight; initializing
2558 verbose stack TypeError: Cannot convert undefined or null to object
2558 verbose stack     at Function.keys (<anonymous>)
2558 verbose stack     at pickVersionFromRegistryDocument (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:125:29)
2558 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
2558 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/pulse-till-done.js:20:8
2558 verbose stack     at saved (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:174:7)
2558 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:241:18
2558 verbose stack     at FSReqWrap.oncomplete (fs.js:111:15)
2559 verbose cwd /Users/ryan/git2consul
2560 error Darwin 17.0.0
2561 error argv "/usr/local/Cellar/node/7.3.0/bin/node" "/usr/local/bin/npm" "install" "git2consul@0.12.11"
2562 error node v7.3.0
2563 error npm  v3.10.10
2564 error Cannot convert undefined or null to object
2565 error If you need help, you may report this error at:
2565 error     <https://github.com/npm/npm/issues>
```

**Comment by solidspark** [comment]
This was a result of the npm outage: http://blog.npmjs.org/post/169432444640/npm-operational-incident-6-jan-2018

Closing.
